export const buttonList = [
    { value: "X", className: "delete" },
    { value: "%", className: null },
    { value: "AC", className: "all-clear" },
    { value: "/", className: "operator" },
    { value: "7", className: null },
    { value: "8", className: null },
    { value: "9", className: null },
    { value: "-", className: "operator" },
    { value: "4", className: null },
    { value: "5", className: null },
    { value: "6", className: null },
    { value: "+", className: "operator" },
    { value: "1", className: null },
    { value: "2", className: null },
    { value: "3", className: null },
    { value: "*", className: "operator" },
    { value: "0", className: null },
    { value: "00", className: null },
    { value: ".", className: "decimal" },
    { value: "=", className: "equal-sign" }
];
